### ISSUE TITLE
Change project name to Jakarta Authorization

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jacc#25]
Background information:
https://waynebeaton.wordpress.com/2019/04/04/renaming-java-ee-specifications-for-jakarta-ee/

Checklist:
- [ ]  GitHub
- [ ]  README file
- [ ]  CONTRIBUTING file
- [x]  Eclipse Project under https://projects.eclipse.org/projects/ee4j

**Comment by ivargrimstad** [comment]
Should we leave out ...Contract for Containers?

**Comment by arjantijms** [comment]
>Should we leave out ...Contract for Containers?

Absolutely, though a concern was raised over at the JASPIC project that we may need to make clear that both JASPIC and JACC are not just your average user facing projects, but more of low-level core projects. I don't think "Contract for Containers" captures that in any way.

*Maybe* Jakarta Authorization Core or Jakarta Core Authorization, would be an option if people really feel strongly about this. Otherwise I'm personally happy with "Jakarta Authorization" and clarifying the core aspect in Javadoc.

**Comment by ggam** [comment]
+1 for Jakarta Authorization.

**Comment by arjantijms** [comment]
Fixed by https://github.com/eclipse-ee4j/jacc/pull/31
